server:
  port: 8005

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8001
          predicates:
            - Path=/users/**
            - Path=/auth/**
        - id: deal-service
          uri: http://localhost:8002
          predicates:
            - Path=/deals/**
        - id: payment-service
          uri: http://localhost:8004
          predicates:
            - Path=/payments/**
        - id: cashback-service
          uri: http://localhost:8006
          predicates:
            - Path=/cashback/**

