feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

